version: '3.8'

services:
  project_db:
    container_name: nest_graphql_db
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    ports:
    - "${DATABASE_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
